version: "3"

services:
  node:
    image: node:17.0.0-alpine
    user: node
    entrypoint: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    env_file: .env
    ports:
      - $SERVER_PORT:$SERVER_PORT
    volumes:
      - .:/home/node

  postgresql:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./postgresql:/var/lib/postgresql/data
